# Generated by Django 6.0.4 on 2026-04-27 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('context', models.TextField()),
                ('chosen_action', models.TextField()),
                ('reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethics', models.CharField(max_length=50)),
                ('risk_level', models.CharField(max_length=50)),
                ('time_scope', models.CharField(max_length=50)),
                ('affected_party', models.CharField(max_length=50)),
                ('justification_quality', models.FloatField()),
                ('confidence', models.FloatField()),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='api.decision')),
            ],
        ),
    ]
